// Generated by scripts/generate-config-stories.mjs. Edit the generator, then regenerate.
import type { Meta, StoryObj } from "@storybook/angular";
import baseMeta, { Default as baseStory } from "../../stepper-container.stories";
import { StepperContainerComponent } from "../../stepper-container.component";
const meta: Meta<StepperContainerComponent> = { ...baseMeta, id: "navigation-stepper-container-recipes", title: "Navigation/Stepper container/Recipes", component: StepperContainerComponent, tags: [], args: { ...baseMeta.args } };
export default meta;
type Story = StoryObj<StepperContainerComponent>;
export const Mobile: Story = { ...baseStory, args: { ...baseStory.args, ...{"label":"A descriptive label that may wrap onto another line"} }, parameters: { viewport: { defaultViewport: "mobile1" }, storyNote: "Verify the component at a narrow mobile width. Content must wrap without horizontal page scrolling, clipped focus rings, or unreachable actions." } };
export const LongContent: Story = { ...baseStory, args: { ...baseStory.args, ...{"label":"A descriptive label that may wrap onto another line"} }, parameters: { storyNote: "Verify long, translated, and enlarged content. The component must preserve meaning, focus order, and access to every action." } };
export const NonDefaultState: Story = { ...baseStory, args: { ...baseStory.args, ...{} }, parameters: { storyNote: "Inspect a supported non-default state and confirm that meaning is conveyed through semantics and text as well as color." } };
