// Generated by scripts/generate-config-stories.mjs. Edit the generator, then regenerate.
import type { Meta, StoryObj } from "@storybook/angular";
import baseMeta, { Default as baseStory } from "../../checkbox.stories";
import { CheckboxComponent } from "../../checkbox.component";
const meta: Meta<CheckboxComponent> = { ...baseMeta, id: "inputs-checkbox-recipes", title: "Inputs/Checkbox/Recipes", component: CheckboxComponent, tags: [], args: { ...baseMeta.args } };
export default meta;
type Story = StoryObj<CheckboxComponent>;
export const Mobile: Story = { ...baseStory, args: { ...baseStory.args, ...{"label":"A descriptive label that may wrap onto another line","description":"Supporting information can be longer than expected, translated, or enlarged without hiding actions or causing horizontal scrolling.","stretch":true} }, parameters: { viewport: { defaultViewport: "mobile1" }, storyNote: "Verify the component at a narrow mobile width. Content must wrap without horizontal page scrolling, clipped focus rings, or unreachable actions." } };
export const LongContent: Story = { ...baseStory, args: { ...baseStory.args, ...{"label":"A descriptive label that may wrap onto another line","description":"Supporting information can be longer than expected, translated, or enlarged without hiding actions or causing horizontal scrolling.","stretch":true} }, parameters: { storyNote: "Verify long, translated, and enlarged content. The component must preserve meaning, focus order, and access to every action." } };
export const NonDefaultState: Story = { ...baseStory, args: { ...baseStory.args, ...{"disabled":true} }, parameters: { storyNote: "Inspect a supported non-default state and confirm that meaning is conveyed through semantics and text as well as color." } };
