// Generated by scripts/generate-config-stories.mjs. Edit the generator, then regenerate.
import type { Meta, StoryObj } from "@storybook/angular";
import baseMeta, { Default as baseStory } from "../../skeleton.stories";
import { SkeletonComponent } from "../../skeleton.component";
const meta: Meta<SkeletonComponent> = { ...baseMeta, id: "feedback-loading-skeleton-recipes", title: "Feedback/Loading skeleton/Recipes", component: SkeletonComponent, tags: [], args: { ...baseMeta.args } };
export default meta;
type Story = StoryObj<SkeletonComponent>;
export const Mobile: Story = { ...baseStory, args: { ...baseStory.args, ...{"label":"A descriptive label that may wrap onto another line"} }, parameters: { viewport: { defaultViewport: "mobile1" }, storyNote: "Verify the component at a narrow mobile width. Content must wrap without horizontal page scrolling, clipped focus rings, or unreachable actions." } };
export const LongContent: Story = { ...baseStory, args: { ...baseStory.args, ...{"label":"A descriptive label that may wrap onto another line"} }, parameters: { storyNote: "Verify long, translated, and enlarged content. The component must preserve meaning, focus order, and access to every action." } };
export const NonDefaultState: Story = { ...baseStory, args: { ...baseStory.args, ...{"loading":true} }, parameters: { storyNote: "Inspect a supported non-default state and confirm that meaning is conveyed through semantics and text as well as color." } };
