// Generated by scripts/generate-config-stories.mjs. Edit the generator, then regenerate.
import type { Meta, StoryObj } from "@storybook/angular";
import baseMeta, { Default as baseStory } from "../../snackbar.stories";
import { SnackbarComponent } from "../../snackbar.component";
const meta: Meta<SnackbarComponent> = { ...baseMeta, id: "feedback-snackbar-recipes", title: "Feedback/Snackbar/Recipes", component: SnackbarComponent, tags: [], args: { ...baseMeta.args } };
export default meta;
type Story = StoryObj<SnackbarComponent>;
export const Mobile: Story = { ...baseStory, args: { ...baseStory.args, ...{"heading":"A clear heading that remains readable on a narrow screen","message":"This longer message verifies wrapping, readable spacing, and action placement when the available width is limited."} }, parameters: { viewport: { defaultViewport: "mobile1" }, storyNote: "Verify the component at a narrow mobile width. Content must wrap without horizontal page scrolling, clipped focus rings, or unreachable actions." } };
export const LongContent: Story = { ...baseStory, args: { ...baseStory.args, ...{"heading":"A clear heading that remains readable on a narrow screen","message":"This longer message verifies wrapping, readable spacing, and action placement when the available width is limited."} }, parameters: { storyNote: "Verify long, translated, and enlarged content. The component must preserve meaning, focus order, and access to every action." } };
export const NonDefaultState: Story = { ...baseStory, args: { ...baseStory.args, ...{} }, parameters: { storyNote: "Inspect a supported non-default state and confirm that meaning is conveyed through semantics and text as well as color." } };
