// Generated by scripts/generate-config-stories.mjs. Edit the generator, then regenerate.
import type { Meta, StoryObj } from "@storybook/angular";
import baseMeta, { Default as baseStory } from "../../sidepanel.stories";
import { SidepanelComponent } from "../../sidepanel.component";
const meta: Meta<SidepanelComponent> = { ...baseMeta, id: "overlays-sidepanel-recipes", title: "Overlays/Sidepanel/Recipes", component: SidepanelComponent, tags: [], args: { ...baseMeta.args } };
export default meta;
type Story = StoryObj<SidepanelComponent>;
export const Mobile: Story = { ...baseStory, args: { ...baseStory.args, ...{"heading":"A clear heading that remains readable on a narrow screen","description":"Supporting information can be longer than expected, translated, or enlarged without hiding actions or causing horizontal scrolling."} }, parameters: { viewport: { defaultViewport: "mobile1" }, storyNote: "Verify the component at a narrow mobile width. Content must wrap without horizontal page scrolling, clipped focus rings, or unreachable actions." } };
export const LongContent: Story = { ...baseStory, args: { ...baseStory.args, ...{"heading":"A clear heading that remains readable on a narrow screen","description":"Supporting information can be longer than expected, translated, or enlarged without hiding actions or causing horizontal scrolling."} }, parameters: { storyNote: "Verify long, translated, and enlarged content. The component must preserve meaning, focus order, and access to every action." } };
export const NonDefaultState: Story = { ...baseStory, args: { ...baseStory.args, ...{"error":"Review this value."} }, parameters: { storyNote: "Inspect a supported non-default state and confirm that meaning is conveyed through semantics and text as well as color." } };
