import { Link } from "react-router-dom";
import { PageToc, ProgressiveSection } from "../../components";

const toc = [
  { id: "overview", label: "Overview" }, { id: "principles", label: "Principles" },
  { id: "foundations", label: "Foundations" }, { id: "components", label: "Components" },
  { id: "workflow", label: "Workflow" }, { id: "get-started", label: "Get started" },
];

export function HomePage() {
  return <div className="mx-auto grid max-w-[1400px] grid-cols-1 px-5 md:px-10 xl:grid-cols-[minmax(0,1fr)_16rem] xl:gap-12"><div className="min-w-0 max-w-4xl">
    <section id="overview" className="scroll-mt-24 py-24 md:py-36"><p className="text-xs font-semibold uppercase tracking-[.22em] text-emerald-300">Arcwell UI / Angular</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold tracking-[-.05em] text-white md:text-8xl">Build coherent products without rebuilding the basics.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-400">Arcwell UI is a configurable Angular design system for responsive application interfaces. It combines reusable components, accessible behavior, design tokens, services, patterns, and developer guidance.</p><div className="mt-10 flex flex-wrap gap-3"><Link className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black" to="/components/button">Explore components</Link><a className="rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold text-white" href="#get-started">Install the library</a></div></section>
    <ProgressiveSection id="principles"><p className="eyebrow">Principles</p><h2 className="home-title">One system, predictable decisions.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Configurable","Inputs, outputs, services, projection, and scoped appearance controls."],["Accessible","Keyboard behavior, focus management, semantic HTML, and reduced motion."],["Composable","Small primitives combine into forms, dashboards, workflows, and overlays."]].map(([title, text]) => <article className="home-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></ProgressiveSection>
    <ProgressiveSection id="foundations"><p className="eyebrow">Foundations</p><h2 className="home-title">Tokens connect every surface.</h2><p className="home-copy">Shared color, typography, spacing, radius, focus, and elevation tokens create consistent light and black glass themes. Component-level tokens allow deliberate overrides without forking component CSS.</p><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-4">{["Color","Type","Spacing","Motion"].map((item) => <div className="rounded-2xl border border-white/10 bg-white/[.025] p-6 text-center text-sm text-zinc-300" key={item}>{item}</div>)}</div></ProgressiveSection>
    <ProgressiveSection id="components"><p className="eyebrow">Components</p><h2 className="home-title">From inputs to complete workflows.</h2><p className="home-copy">The catalog covers actions, layout, data display, feedback, inputs, navigation, and overlays. Every API documents its configuration, variations, outputs, patterns, and appearance controls.</p><div className="mt-8 flex flex-wrap gap-2">{["Button","Card","Input","Dropdown","Modal","Tiles","Tabs","Notifications"].map((name) => <span className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm" key={name}>{name}</span>)}</div></ProgressiveSection>
    <ProgressiveSection id="workflow"><p className="eyebrow">Workflow</p><h2 className="home-title">Designed for people and tools.</h2><div className="mt-10 grid gap-4 md:grid-cols-2"><article className="home-card"><h3>For developers</h3><p>Live components, copyable Angular examples, precise types, emitted payloads, responsive behavior, and accessibility guidance.</p></article><article className="home-card"><h3>For automation</h3><p>The same verified source generates documentation, Storybook guidance, component skills, and MCP context, reducing drift.</p></article></div></ProgressiveSection>
    <ProgressiveSection id="get-started"><p className="eyebrow">Get started</p><h2 className="home-title">Add Arcwell UI.</h2><pre className="mt-8 overflow-x-auto rounded-2xl border border-white/10 bg-[#090909] p-5 text-sm text-emerald-300"><code>npm install @arcwell/ui</code></pre><p className="home-copy mt-6">Import the library stylesheet once, then import standalone components where they are used.</p><Link className="mt-8 inline-block rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black" to="/components/card">Read component documentation</Link></ProgressiveSection>
  </div><PageToc items={toc} /></div>;
}
