// Generated by scripts/generate-config-stories.mjs. Edit the generator, then regenerate.
import type { Meta, StoryObj } from "@storybook/angular";
import baseMeta, { Default as baseStory } from "../../header.stories";
import { HeaderComponent } from "../../header.component";
const meta: Meta<HeaderComponent> = { ...baseMeta, id: "layout-header-recipes", title: "Layout/Header/Recipes", component: HeaderComponent, tags: [], args: { ...baseMeta.args } };
export default meta;
type Story = StoryObj<HeaderComponent>;
export const Mobile: Story = { ...baseStory, args: { ...baseStory.args, ...{"heading":"A clear heading that remains readable on a narrow screen"} }, parameters: { viewport: { defaultViewport: "mobile1" }, storyNote: "Verify the component at a narrow mobile width. Content must wrap without horizontal page scrolling, clipped focus rings, or unreachable actions." } };
export const LongContent: Story = { ...baseStory, args: { ...baseStory.args, ...{"heading":"A clear heading that remains readable on a narrow screen"} }, parameters: { storyNote: "Verify long, translated, and enlarged content. The component must preserve meaning, focus order, and access to every action." } };
export const NonDefaultState: Story = { ...baseStory, args: { ...baseStory.args, ...{} }, parameters: { storyNote: "Inspect a supported non-default state and confirm that meaning is conveyed through semantics and text as well as color." } };
