import type { ComponentDoc } from "../types";

export interface ComponentSummary { slug: string; title: string; category: string; }

export const componentCatalog: ComponentSummary[] = [
  { slug: "alert", title: "Alert", category: "Feedback" },
  { slug: "avatar", title: "Avatar", category: "Data display" },
  { slug: "badge", title: "Badge", category: "Data display" },
  { slug: "button", title: "Button", category: "Actions" },
  { slug: "card", title: "Card", category: "Layout" },
  { slug: "input", title: "Input", category: "Inputs" },
  { slug: "progress", title: "Progress", category: "Feedback" },
  { slug: "toggle", title: "Toggle", category: "Inputs" },
  { slug: "fab-button", title: "FAB button", category: "Actions" },
  { slug: "icon-button", title: "Icon button", category: "Actions" },
  { slug: "code-block", title: "Code block", category: "Data display" },
  { slug: "divider", title: "Divider", category: "Layout" },
  { slug: "list", title: "List", category: "Data display" },
  { slug: "tiles", title: "Tiles", category: "Data display" },
  { slug: "global-notification", title: "Global notification", category: "Feedback" },
  { slug: "inline-notification", title: "Inline notification", category: "Feedback" },
  { slug: "skeleton", title: "Loading skeleton", category: "Feedback" },
  { slug: "snackbar", title: "Snackbar", category: "Feedback" },
  { slug: "toast", title: "Toast", category: "Feedback" },
  { slug: "icon", title: "Icon", category: "Data display" },
  { slug: "checkbox", title: "Checkbox", category: "Inputs" },
  { slug: "chips", title: "Chips", category: "Inputs" },
  { slug: "context-selector", title: "Context selector", category: "Inputs" },
  { slug: "counter-button", title: "Counter button", category: "Inputs" },
  { slug: "counter", title: "Counter", category: "Inputs" },
  { slug: "datepicker", title: "Datepicker", category: "Inputs" },
  { slug: "dropdown", title: "Dropdown", category: "Inputs" },
  { slug: "multi-select", title: "Multi-select dropdown", category: "Inputs" },
  { slug: "number-input", title: "Number input", category: "Inputs" },
  { slug: "radio", title: "Radio", category: "Inputs" },
  { slug: "range-selector", title: "Range selector", category: "Inputs" },
  { slug: "segmented-buttons", title: "Segmented buttons", category: "Inputs" },
  { slug: "validation", title: "Validation directive", category: "Inputs" },
  { slug: "container", title: "Container", category: "Layout" },
  { slug: "header", title: "Header", category: "Layout" },
  { slug: "pane", title: "Pane", category: "Layout" },
  { slug: "section", title: "Section", category: "Layout" },
  { slug: "breadcrumb", title: "Breadcrumb", category: "Navigation" },
  { slug: "carousel", title: "Carousel directive", category: "Navigation" },
  { slug: "link", title: "Link directive", category: "Navigation" },
  { slug: "step", title: "Step", category: "Navigation" },
  { slug: "stepper-container", title: "Stepper container", category: "Navigation" },
  { slug: "tab-container", title: "Tab container", category: "Navigation" },
  { slug: "tab", title: "Tab", category: "Navigation" },
  { slug: "bottom-sheet", title: "Bottom sheet", category: "Overlays" },
  { slug: "confirmation-dialog", title: "Confirmation dialog", category: "Overlays" },
  { slug: "modal", title: "Modal", category: "Overlays" },
  { slug: "popover", title: "Popover directive", category: "Overlays" },
  { slug: "sidepanel", title: "Sidepanel", category: "Overlays" },
  { slug: "tooltip", title: "Tooltip directive", category: "Overlays" }
];

export const componentLoaders: Record<string, () => Promise<ComponentDoc>> = {
  "alert": () => import("./alert/docs.json").then((module) => module.default as ComponentDoc),
  "avatar": () => import("./avatar/docs.json").then((module) => module.default as ComponentDoc),
  "badge": () => import("./badge/docs.json").then((module) => module.default as ComponentDoc),
  "button": () => import("./button/docs.json").then((module) => module.default as ComponentDoc),
  "card": () => import("./card/docs.json").then((module) => module.default as ComponentDoc),
  "input": () => import("./input/docs.json").then((module) => module.default as ComponentDoc),
  "progress": () => import("./progress/docs.json").then((module) => module.default as ComponentDoc),
  "toggle": () => import("./toggle/docs.json").then((module) => module.default as ComponentDoc),
  "fab-button": () => import("./fab-button/docs.json").then((module) => module.default as ComponentDoc),
  "icon-button": () => import("./icon-button/docs.json").then((module) => module.default as ComponentDoc),
  "code-block": () => import("./code-block/docs.json").then((module) => module.default as ComponentDoc),
  "divider": () => import("./divider/docs.json").then((module) => module.default as ComponentDoc),
  "list": () => import("./list/docs.json").then((module) => module.default as ComponentDoc),
  "tiles": () => import("./tiles/docs.json").then((module) => module.default as ComponentDoc),
  "global-notification": () => import("./global-notification/docs.json").then((module) => module.default as ComponentDoc),
  "inline-notification": () => import("./inline-notification/docs.json").then((module) => module.default as ComponentDoc),
  "skeleton": () => import("./skeleton/docs.json").then((module) => module.default as ComponentDoc),
  "snackbar": () => import("./snackbar/docs.json").then((module) => module.default as ComponentDoc),
  "toast": () => import("./toast/docs.json").then((module) => module.default as ComponentDoc),
  "icon": () => import("./icon/docs.json").then((module) => module.default as ComponentDoc),
  "checkbox": () => import("./checkbox/docs.json").then((module) => module.default as ComponentDoc),
  "chips": () => import("./chips/docs.json").then((module) => module.default as ComponentDoc),
  "context-selector": () => import("./context-selector/docs.json").then((module) => module.default as ComponentDoc),
  "counter-button": () => import("./counter-button/docs.json").then((module) => module.default as ComponentDoc),
  "counter": () => import("./counter/docs.json").then((module) => module.default as ComponentDoc),
  "datepicker": () => import("./datepicker/docs.json").then((module) => module.default as ComponentDoc),
  "dropdown": () => import("./dropdown/docs.json").then((module) => module.default as ComponentDoc),
  "multi-select": () => import("./multi-select/docs.json").then((module) => module.default as ComponentDoc),
  "number-input": () => import("./number-input/docs.json").then((module) => module.default as ComponentDoc),
  "radio": () => import("./radio/docs.json").then((module) => module.default as ComponentDoc),
  "range-selector": () => import("./range-selector/docs.json").then((module) => module.default as ComponentDoc),
  "segmented-buttons": () => import("./segmented-buttons/docs.json").then((module) => module.default as ComponentDoc),
  "validation": () => import("./validation/docs.json").then((module) => module.default as ComponentDoc),
  "container": () => import("./container/docs.json").then((module) => module.default as ComponentDoc),
  "header": () => import("./header/docs.json").then((module) => module.default as ComponentDoc),
  "pane": () => import("./pane/docs.json").then((module) => module.default as ComponentDoc),
  "section": () => import("./section/docs.json").then((module) => module.default as ComponentDoc),
  "breadcrumb": () => import("./breadcrumb/docs.json").then((module) => module.default as ComponentDoc),
  "carousel": () => import("./carousel/docs.json").then((module) => module.default as ComponentDoc),
  "link": () => import("./link/docs.json").then((module) => module.default as ComponentDoc),
  "step": () => import("./step/docs.json").then((module) => module.default as ComponentDoc),
  "stepper-container": () => import("./stepper-container/docs.json").then((module) => module.default as ComponentDoc),
  "tab-container": () => import("./tab-container/docs.json").then((module) => module.default as ComponentDoc),
  "tab": () => import("./tab/docs.json").then((module) => module.default as ComponentDoc),
  "bottom-sheet": () => import("./bottom-sheet/docs.json").then((module) => module.default as ComponentDoc),
  "confirmation-dialog": () => import("./confirmation-dialog/docs.json").then((module) => module.default as ComponentDoc),
  "modal": () => import("./modal/docs.json").then((module) => module.default as ComponentDoc),
  "popover": () => import("./popover/docs.json").then((module) => module.default as ComponentDoc),
  "sidepanel": () => import("./sidepanel/docs.json").then((module) => module.default as ComponentDoc),
  "tooltip": () => import("./tooltip/docs.json").then((module) => module.default as ComponentDoc)
};
